name: AARON SILLIS
favicon: null
layout_spectrum: 0.7657773748505861
typography_spectrum: 0.9176185026299208
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.8435225449502468
  lightness: 0.9172492092475295
  saturation: 0.8946142783388495
  rhythmicContrast: 0.4193964758887887
purpose: []
